# Array Iteration

# Iterating 1D array

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


# Iterating 2D array

In [7]:
arr=np.array([[1,2,3],[4,5,6]])
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [8]:
arr=np.array([[1,2,3],[4,5,6]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


# Iterating 3-D Arrays

In [9]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
    print("i represents 2D array:\n")
    print(i)

i represents 2D array:

[[1 2 3]
 [4 5 6]]
i represents 2D array:

[[ 7  8  9]
 [10 11 12]]


# Iterating 3-D Arrays using nditer()

In [10]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Enumerated Iteration Using ndenumerate()

In [12]:
arr = np.array([1,2,3,4])
for idx, i in np.ndenumerate(arr):
    print(idx, i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [13]:
arr = np.array([[1,2],[3,4]])
for idx, i in np.ndenumerate(arr):
    print(idx, i)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [14]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for idx, i in np.ndenumerate(arr):
    print(idx, i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
