In [1]:
import numpy as np
n2 = np.ones(2)           #here 2 is no.of elements of array
print(n2)

[1. 1.]


In [2]:
import numpy as np
n2 = np.ones([3,4])     #here [4,3] is dimension of array i.e., 4x3 
print(n2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
