In [1]:
import numpy as np
n1 = np.array([10,20,30,40,50])
n2 = np.array([50,60,70,80,90])
np.intersect1d(n1,n2) #intersection of n1 and n2

array([50])

In [1]:
import numpy as np
n1 = np.array([10,20,30,40,50])
n2 = np.array([50,60,70,80,90])
np.setdiff1d(n1,n2)        #n1-n2

array([10, 20, 30, 40])

In [4]:
import numpy as np
n1 = np.array([[10,20],[30,40],[50,60]])
n2 = np.array([[50,60],[70,80],[90,100]])
np.setdiff1d(n2,n1)       #n2-n1

array([ 70,  80,  90, 100])

In [4]:
# Basic Addition, subtraction, Multiplication and Division

In [5]:
import numpy as np
n1 = np.array([100,200,300])
n2 = np.array([1,2,3])

In [6]:
#add all values of n1 by 2
n1 = n1+2                
print(n1)

[102 202 302]


In [7]:
#multiply all values of n2 by 3
n2 = n2 * 3           
print(n2)

[3 6 9]


In [8]:
 #divide all values of n2 by 3
n2 = n2 / 3          
n2

array([1., 2., 3.])

In [9]:
#subtract all values of n1 by 1
n1 = n1 - 1          
n1

array([101, 201, 301])

In [2]:
import numpy as np
n10 = np.array([10,20,30,40,50])
n10.T

array([10, 20, 30, 40, 50])